### ISSUE TITLE
Dont use json

### ISSUE THREAD

**Issue by mezotv** [falcao-g/Falbot#1]
Please use dotenv files for important stuff like tokens, mongodb urls and apikeys. .env files are more secure than using normal jsons so please switch to them

**Comment by falcao-g** [comment]
hi, first of all, thank you for the suggestion, I've put the important stuff (bot token, mongodb url and api key) in a .env file like you said. 

But there were values in the config.json file that needed to be an array of strings for example and apparently .env files only support strings, so I left those where they are as they are not really a secret.

Is it fine this way or should I switch all values into the .env file?

Thanks again

**Comment by mezotv** [comment]
You can keep arrays etc in the config file just not any important tokens

**Comment by falcao-g** [comment]
Yeah that was exactly what i did, i will be closing the issue now and updating the readme to contemplate this changes, thank you for the feedback
