### ISSUE TITLE
Criar um comando de "exchange"

### ISSUE THREAD

**Issue by falcao-g** [falcao-g/Falbot#32]
### Descrição
Agora que temos um sistema de inventário consolidado e robusto, seria interessante criar um comando de troca, onde um usuário propõe uma troca para outro usuário e caso ele aceite, a troca acontece, por exemplo, eu ofereço para outro usuário 10 mil falcoins e 5 cordas por 5 diamantes

### Como implementar?
Será a implementação básica de um comando, a parte mais complexa será processar todos os itens do input, recomendo indicar pro usuário que coloque a quantidade, depois o nome e separe ele com vírgulas, exemplo: "50m falcoins, 10 pedras, 5 cordas"

**Comment by AmarilhaTiago** [comment]
I'll work on that, mate, coming soon!
