### ISSUE TITLE
Sugestão automática de itens

### ISSUE THREAD

**Issue by falcao-g** [falcao-g/Falbot#35]
### Descrição

No momento, temos vários comandos que recebem um item como argumento, portanto, seria mais eficiente usarmos um autocomplete similar ao do comando math para irmos sugerindo para o usuário qual item ele deseja escrever, isso ajudaria até a definir quais itens alguns comandos como o construir e o equipar podem receber, já que os usuários só conseguem mandar o que está aparecendo no autocomplete, então no construir sugerimos só itens que podem ser construídos e no equipar sugerimos só itens que podem ser equipados

### Como implementar?

Temos que olhar o código do comando math e analisar como ele lida com o autocomplete, mas claro que precisamos pegar os itens que são relevantes para aquele comando, analisar o que o usuário está digitando e sugerir um item, usando .startsWith() e .toLowerCase() muito provavelmente

**Comment by Vicarillous** [comment]
Concordo
