### ISSUE TITLE
Quanto devem valer os items que são construídos?

### ISSUE THREAD

**Issue by falcao-g** [falcao-g/Falbot#37]
### Descrição
No momento temos 3 categorias de itens que são construídos levando em conta seus valores, temos os itens que valem menos que a soma do valor de seus ingredientes, como por exemplo a panqueca que vale 800 e seus ingredientes valem 4800, temos os que valem exatamente o mesmo, como as ferramentas, e temos itens que valem mais que a soma de seus ingredientes, como a bola, que vale 23.900 e seus ingredientes valem 20.400

Imagino que os itens que só servem para serem vendidos, deveriam valer, pelo menos, a soma do valor de seus ingredientes, e os itens que realmente tem uma funcionalidade, devem valer mais que isso, por exemplo a picareta de ferro que serve para ser equipada e ganhar mais itens, ela deveria valer mais que a soma de seus ingredientes?

gostaria de ajuda nessa dúvida

**Comment by EsterAmorim** [comment]
Acredito q itens de loot poderiam ter pelo menos 10% de acréscimo no seu valor de venda, pois da trabalho para construir
