### ISSUE TITLE
Tradução para espanhol

### ISSUE THREAD

**Issue by falcao-g** [falcao-g/Falbot#38]
### Descrição
Como o Falbot é um bot brasileiro, e agora temos um sistema mais robusto de mensagens, está na hora de implementarmos mais idiomas nele, assim, o espanhol é um ótimo para começar

### Como implementar?
Para todas as mensagens no messages.json, e para todos os itens no items.json, precisamos colocar um novo campo -> "es-ES": "texto-em-espanhol" 😃

**Comment by Vicarillous** [comment]
Si hermanito!
