### ISSUE TITLE
Leaderboard item autocomplete not working

### ISSUE THREAD

**Issue by falcao-g** [falcao-g/Falbot#99]
### Description of the bug

The autocomplete from /leaderboard item is not working, 

that is because the bot analyzes with .startsWith() and all items start with emojis, so you can just search with emojis, this issue is fixed in the /inventory commands so we can just copy the code from there

### Steps to reproduce

use /leaderboard item and try to get the bot to autocomplete any item

### Media, if necessary

![image](https://github.com/falcao-g/Falbot/assets/60127788/38a3b1ac-da3f-407e-9646-04175da88ec3)

**Comment by maazshakeel** [comment]
Hey, I'd like to work on this issue, can I be assigned?

**Comment by falcao-g** [comment]
Of course! thanks for the help
